### ISSUE TITLE
Compatibility with launcher?

### ISSUE THREAD

**Issue by edoreld** [SomeDeadGuy/UndeadPeopleTileset#64]
Hi there,

I've come across your tileset and I love the aesthetic!

I'm using the launcher (https://github.com/remyroy/CDDA-Game-Launcher) but I can't make your texture pack work there. I have followed the instructions below:
```
Download archive, put folders data and gfx from TILESET folder in Cataclysm Installation folder (where cataclysm-tiles.exe is), in the game choose UNDEAD_PEOPLE (NEW VERSION) or UNDEAD_PEOPLE_LEGACY tileset in Settings->Options->Graphics->Choose Tileset
```

I did all that, putting the folders into using C:<user-path>\AppData\Local\Programs\CDDA Game Launcher\cdda

When I launch the game, I see the tileset on the settings, but the textures don't load. I checked the log and it shows the following trace: https://gist.github.com/edoreld/a2ea238a28dd5a890148f65593be67ec

Any ideas of how to make it work?

**Comment by SomeDeadGuy** [comment]
no, you doing it wrong
launcher is a program what INSTALLS your DDA in to a specific folder.
Path to this folder should be in launcher and you should install my tileset in to folder with DAA, not in folder with launcher.
I do not use launcher, it is very easy to install and update the game by hand. Also i would not recommend launcher because it will at some point delete my tileset or 3rd party mods after it updates. Be aware.

**Comment by SomeDeadGuy** [comment]
Close this issue if you figured it out or ask additional questions if you have them.

**Comment by edoreld** [comment]
The launcher is installed on "<some-path>\CDDA Game Launcher" and the game is installed on "<some-path>\CDDA Game Launcher\cdda". On this cdda directory is where I found the file cataclysm-tiles.exe. This is where I dragged the data and gfx folders.

**Comment by edoreld** [comment]
Never mind, I got it working. I had it working before, I just thought it was a different (similar) tileset. Thanks for the help!
